### ISSUE TITLE
Preferred way to handle amqp link redirects

### ISSUE THREAD

**Issue by digimaun** [Azure/azure-uamqp-python#10]
What is the preferred pattern/mechanism to follow amqp redirect links? For example in the case when the IoT Hub redirects to its event hub endpoint.

**Comment by annatisch** [comment]
I've opened an issue in the C library to discuss. The changes required to this library will depend on how we approach the issue in the C library. Stay tuned :)

https://github.com/Azure/azure-uamqp-c/issues/231

**Comment by annatisch** [comment]
Thanks @digimaun - Link redirects are now supported.
See the IotHub test here for a sample:
- Receive: [samples/test_azure_iothub_receive.py](https://github.com/Azure/azure-uamqp-python/blob/master/samples/test_azure_iothub_receive.py)
- Receive async: [samples/test_azure_iothub_receive_async.py](https://github.com/Azure/azure-uamqp-python/blob/master/samples/test_azure_iothub_receive_async.py)
