### ISSUE TITLE
Update Windows build support to VS2019

### ISSUE THREAD

**Issue by bsiegel** [Azure/azure-uamqp-python#122]
Right now the project can't build under VS2019, which is causing our Windows CI builds to have to stay on an older agent image. We should get this working under VS2019. Unfortunately just updating setuptools to >=34.4.0 and changing the CMake target is not enough, there are some platform problems that need to be resolved:

Python 3.5:
It's unable to locate a header file. My initial scan of this seems to indicate that as compared to the other Python version builds, the call to cl.exe is missing a number of include directories. This leads me to think that something in this version of Python (maybe distutils?) is too old to know how to locate those directories. We might have to figure out how to add them manually or whether there is just some component we can update with pip.

Python 3.6 x86:
This is odd because the x64 build passes. The x86 build always fails with a linker error, unresolved external symbol __except_handler4_common. I've tried using the -T host=x86 CMAKE flags to use the 32-bit compiler toolchain, the flag worked as documented but that didn't resolve the issue. At this point I'm a little stumped as to why this is happening and only for the x86 build.

**Comment by bsiegel** [comment]
Exploratory PR: #121

**Comment by hellodhana** [comment]
Following this issue as I am having same build issue with respect to VS2019.

**Comment by bsiegel** [comment]
> Following this issue as I am having same build issue with respect to VS2019.

Thanks @hellodhana, can you thumbs-up this issue to help us track its impact?

**Comment by hellodhana** [comment]
Done. Thanks

**Comment by yunhaoling** [comment]
as dropping off python 2.7, we can and have already updated to setup.py to adopt VS2019 recently.
