### ISSUE TITLE
Errors in version 1.2.3 and later

### ISSUE THREAD

**Issue by ian-young-sydney** [Azure/azure-uamqp-python#134]
I seem to have found an issue when using the azure-eventhub-1.3.2 library with ‘uamqp’ version 1.2.3 and later. Version 1.2.2 doesn't seem to have the issue.  Basically, I quickly get errors when I connect to the EventHub using the following code:

```
import asyncio
from azure.eventhub import EventHubClient, Sender, EventData, EventHubClientAsync

async def main():
    address = "amqps://.....servicebus.windows.net/...."
    user = ...
    password = ...

    client = EventHubClientAsync(address, debug=False, username=user, password=password)
    sender = client.add_async_sender()
    await client.run_async()

    while True:
        try:
            event_str = "test message"
            event_data = EventData(event_str)
            print('Sending Event data {} to eventhub'.format(event_str))

            await sender.send(event_data)
            await asyncio.sleep(1)

        except Exception as e: 
            print (f"caught excetpion {e}")
            await asyncio.sleep(1)


    await client.stop_async()

loop = asyncio.get_event_loop()
loop.run_until_complete(main())
loop.close()
```

This code simply connects to the EventHub, sends a message, and sleeps for a second.  The first 2 or 3 messages go through, and then it usually gets disconnected and is not retry-able.  You have to disconnect and reconnect again to make it work.  The output messages I got were:

```
> python3 ./eventhub_sender.py
Sending Event data test message to eventhub
Sending Event data test message to eventhub
Sending Event data test message to eventhub
Sending Event data test message to eventhub
caught excetpion Send failed: Message send failed with result: MessageSendResult.Timeout
Sending Event data test message to eventhub
caught excetpion Send failed: Message send failed with result: MessageSendResult.Timeout
Sending Event data test message to eventhub
caught excetpion Send failed: Message send failed with result: MessageSendResult.Timeout
Sending Event data test message to eventhub
caught excetpion Send failed: Message send failed with result: MessageSendResult.Timeout
Sending Event data test message to eventhub
caught excetpion Send failed: Message send failed with result: MessageSendResult.Timeout
```

I tried using the new Python SDK (azure-eventhub-5.0.0r6) against the 1.2.4 library and it seems fine, but when I use (azure-eventhub-1.3.2) against this, it's breaking.  The code changes in version 1.2.3 seems to have broken something in the older version.

Note, I'd like to be using the new Python SDK, but it's still beta and not ready for production.  I should be able to move over to these libraries when they are stable.  In the meantime, this issue should be resolved.

**Comment by yunhaoling** [comment]
Hi @ian-young-sydney ,

we've noticed the problem in eh 1.3.2: https://github.com/Azure/azure-sdk-for-python/issues/8902.

We've released eventhub 1.3.3 today (uamqp 1.2.5 was released last week) which should have the problem fixed. Can you try the latest library?

**Comment by ian-young-sydney** [comment]
Hi @yunhaoling ,

Thanks for the new release.  I tested my simple script with the new version and it's working.  I'm going to run some more testing today but I think it's good.  I noticed that you and others have made various improvements to this eventhub library, which I am very thankful for.  The new one is still beta so hesitant to migrate our services to this for Prod, so keen for bug fixes to be applied for Prod.  Also keen for general improvements to this and the new SDK in the Future!  Nice work!

**Comment by yunhaoling** [comment]
Hi @ian-young-sydney ,

You're welcome, glad that our work helps you!
We'll let you know once the new EventHubs SDK comes to the GA stage.

Please feel free to reach out to us if any help is needed.
Closing this issue for now but you can always re-open it if the problem still exists.
