### ISSUE TITLE
Queue name includes host address and scheme

### ISSUE THREAD

**Issue by Counterfly** [Azure/azure-uamqp-python#164]
- **UAMQP 1.2.9**: 
- **OSX 10.15.6**:
- **python 3.7.7**: 

**Describe the bug**
The queue name is composed of the host, scheme, and path address.

**To Reproduce**
```
import uamqp
import uamqp.message
from uamqp.authentication.common import SASLPlain
from urllib.parse import urlparse
from uamqp import authentication

import json
def uamqp_send_simple():
    msg_content = json.dumps({ "key": "Hello world"})

    url = "0.0.0.0"
    port = 5671
    user = ""
    password = ""
    path = "queue1"

    uri = f"amqps://${url}/${path}"
    auth = SASLPlain(
        username=user,
        password=password,
        hostname=url,
        port=port
    )
    parsed_uri = urlparse(uri)

    msg = uamqp.message.Message(body=msg_content)

    sender = uamqp.SendClient(
        uri,
        auth=auth,
        # how long the thread will sleep (in seconds) between pinging the connection
        #TODO: set as env var if this works
        keep_alive_interval=2,
        client_name=f"AMQP Sending Thread for {uri}",
        debug=True
    )

    sender.send_message(msg)
    print("Message sent!")
    sender.close()

if __name__ == "__main__":
    uamqp_send_simple()
```

**Expected behavior**
The queue name (on activeMQ) should be "queue1". but is "amqps://0.0.0.0/queue1"

**Comment by yunhaoling** [comment]
hey @Counterfly, sorry I didn't quite follow the bug you mentioned. May I ask a few more questions to better understand your situation?

1. for the **Expected behavior** part, the `queue_name` you mentioned is the parameter used for constructing SendClient?
Current uamqp client constructor only supports full uri -- `SendClient(target='amqps://host_address/queue_name',...)`, or are you referring to some other "queue_name" property/variable/parameter?
2. on you using the library to connect to your own activeMQ server or azure service?

**Comment by Counterfly** [comment]
hey.

1. yes, the parameter is the `target` variable (in this case the `path` of the url) and that's just because I don't see anywhere else to specify the queue name.
2. No, i'm using it to connect to a local (my own) activeMQ server. Not to an azure service.

**Comment by yunhaoling** [comment]
hey @Counterfly , sorry for the delayed response.

I double-checked the concepts in AMQP sepc -- http://docs.oasis-open.org/amqp/core/v1.0/amqp-core-complete-v1.0.pdf

I'm afraid from the view of protocol, "queue" is not a concept that AMQP implementation should be aware of. Here is why:

In AMQP, the endpoints that amqp link connects are known as sources and targets. In **section 3.5 sources and targets**, the protocol says:
```
The messaging layer defines two concrete types (source and target) to be used as the source and target of a
link. These types are supplied in the source and target fields of the attach frame when establishing or resuming
link. The source is comprised of an address (which the container of the outgoing link endpoint will resolve to a
node within that container) coupled with properties which determine:
• which messages from the sending node will be sent on the link,
• how sending the message affects the state of that message at the sending node,
• the behavior of messages which have been transferred on the link, but have not yet reached a terminal state
at the receiver, when the source is destroyed.
```

A source/target could be any computing node that supports the amqp protocol and that node doesn't necessarily need to be limited to the concept of "queue" -- in Azure EventHub, the node is known as "eventhub", in Azure ServiceBus, the node is known as "topic"/"subscription"/"queue".

So the amqp implementation should accept source/target uri as the spec describes, but you could construct the source/target address by yourself or add layer of abstraction if wanted.

e.g. in azure-servicebus sdk, we manually construct target uri: https://github.com/Azure/azure-sdk-for-python/blob/8f286b8b897f0295d471dce30bee235fa5db078f/sdk/servicebus/azure-servicebus/azure/servicebus/_common/receiver_mixins.py#L34

**Comment by yunhaoling** [comment]
I'm closing this issue. Let me know whether the explanation makes sense to you or we could discuss further.
