### ISSUE TITLE
Footer and Delivery_Annotations do not appear to persist across send->receive

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-uamqp-python#169]
- **UAMQP Package Version**: 
1.2.10
- **Operating System**:
Windows (Assumed all)
- **Python Version**: 
3.8 (Assumed all)

**Describe the bug**
Setting values within the footer and delivery annotation dicts (or setting them as novel dicts) and then sending a message does not result in those same values showing up on the received message.

**To Reproduce**
1. Create a Message object.
2. Set message.footer = {b"foo":1} (and message.delivery_annotations = {b"bar":2}
3. Send the message via a SendClient
4. Receive the message via a ReceiveClient
5. observe that message.footer and delivery_annotations do not have the keys set above.

**Expected behavior**
footer and delivery_annotations should persist the same values populated at send-time

**Additional context**
I would note that I checked the AMQP spec for information about footer/delivery_annotations to check if they were "special" for whatever reason.  delivery_annotations had verbiage surrounding "Delivery specific" which I could MAYBE take to infer as "only to the broker?" but wasn't sure, and the additional information off the UAMQP spec listing valid keys was a helpfully blank page.  Figured I'd drop this here just in case it's a breadcrumb worth noting.

Finally, I would note this bug was found via ServiceBus, on the off chance its utilization has bearing on these symptoms.

**Comment by yunhaoling** [comment]
this is fixed in the latest uamqp v1.2.11 release
