### ISSUE TITLE
Sending fails if an application property's value is a string of length 1

### ISSUE THREAD

**Issue by zach-b** [Azure/azure-uamqp-python#17]
If one of the application properties' value is a string of length 1 (as an example, "t"), the application is unable to send (for both the async and sync senders).

## Error message:
Message error, 3 retries exhausted (an integer is required)
uamqp.errors.MessageSendFailed: Failed to send message.

## Code to reproduce: (slight modification of the repository samples)
    application_properties={"test": "t"}
    msg_content = b"hello world"

    message = uamqp.Message(msg_content, application_properties=application_properties)

    uri = "sb://{}/{}".format(live_eventhub_config['hostname'], live_eventhub_config['event_hub'])
    sas_auth = authentication.SASTokenAuth.from_shared_access_key(
        uri, live_eventhub_config['key_name'], live_eventhub_config['access_key'])

    target = "amqps://{}/{}".format(live_eventhub_config['hostname'], live_eventhub_config['event_hub'])
    send_client = uamqp.SendClient(target, auth=sas_auth, debug=False)
    send_client.send_message(message, close_on_done=True)

**Comment by annatisch** [comment]
Thanks @zach-b!
I will take a look at this today :)

**Comment by annatisch** [comment]
This is now fixed in rc2.
