### ISSUE TITLE
CBS Auth errors when trying to use a SAS token without a se= stanza

### ISSUE THREAD

**Issue by KieranBrantnerMagee** [Azure/azure-uamqp-python#170]
- **UAMQP Package Version**: 
latest
- **Operating System**:
all
- **Python Version**: 
all

**Describe the bug**
Utilize a SAS token lacking a &se=<expiry timestamp> stanza.  Observe the following error:
E                   uamqp.errors.TokenAuthFailure: CBS Token authentication failed.
E                   Status code: 500
E                   Description: The service was unable to process the request; please retry the operation. For more information on exception types and proper exception handling, please refer to http://go.microsoft.com/fwlink/?LinkId=761101

**To Reproduce**
1.  Generate a SAS token as observed in [this ](https://github.com/Azure/azure-sdk-for-python/pull/13627)Service Bus test
2. Try to authenticate/send/do any operation

**Expected behavior**
Should succeed to authenticate.

**Comment by yunhaoling** [comment]
Closing this issue now, the summary is as bellow:

Based on 
 - The MS doc on how to generate a SAS token: https://docs.microsoft.com/en-us/rest/api/eventhub/generate-sas-token
 - The implementation in uamqp-c on how to generate SAS token: https://github.com/Azure/azure-uamqp-python/blob/ccc9c82a548a42b147c11ae6a46575bd3b03ea24/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/src/sastoken.c#L205

We conclude that "se="  is required parameter and the expiry information is included in the token string to be hashed.

**Comment by yunhaoling** [comment]
new action item for you @KieranBrantnerMagee: we may need to remove the optionality in SB.
