### ISSUE TITLE
Binary executables checked in the git repository

### ISSUE THREAD

**Issue by bluca** [Azure/azure-uamqp-python#209]
Since PR https://github.com/Azure/azure-uamqp-python/pull/200 a number of binary executable files have been checked in the git repository:

```
src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/deps/azure-macro-utils-c/macro_utils_h_generator/macro_utils_h_generator.vshost.exe
src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/deps/umock-c/deps/azure-macro-utils-c/macro_utils_h_generator/macro_utils_h_generator.vshost.exe
src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/deps/umock-c/deps/ctest/deps/azure-macro-utils-c/macro_utils_h_generator/macro_utils_h_generator.vshost.exe
src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/deps/umock-c/deps/testrunner/deps/azure-macro-utils-c/macro_utils_h_generator/macro_utils_h_generator.vshost.exe
src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/testtools/ctest/deps/azure-macro-utils-c/macro_utils_h_generator/macro_utils_h_generator.vshost.exe
src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/testtools/testrunner/deps/azure-macro-utils-c/macro_utils_h_generator/macro_utils_h_generator.vshost.exe
src/vendor/azure-uamqp-c/deps/azure-c-testrunnerswitcher/deps/azure-macro-utils-c/macro_utils_h_generator/macro_utils_h_generator.vshost.exe
src/vendor/azure-uamqp-c/deps/azure-ctest/deps/azure-macro-utils-c/macro_utils_h_generator/macro_utils_h_generator.vshost.exe
src/vendor/azure-uamqp-c/deps/azure-macro-utils-c/macro_utils_h_generator/macro_utils_h_generator.vshost.exe
src/vendor/azure-uamqp-c/deps/umock-c/deps/azure-macro-utils-c/macro_utils_h_generator/macro_utils_h_generator.vshost.exe
src/vendor/azure-uamqp-c/deps/umock-c/deps/ctest/deps/azure-macro-utils-c/macro_utils_h_generator/macro_utils_h_generator.vshost.exe
src/vendor/azure-uamqp-c/deps/umock-c/deps/testrunner/deps/azure-macro-utils-c/macro_utils_h_generator/macro_utils_h_generator.vshost.exe
```

Was this the result of a git add -A mistake?

Could you please remove them? Having binary files checked in git is not great as git notoriously does not handle binaries well (without extensions like git-lfs), and will inflate the repository size massively.

Also and more importantly, they introduce huge compliance and licensing issues for distributors, Linux distributions and packages.

**Comment by annatisch** [comment]
Thanks @bluca! This does appear to be a mistake....
@yunhaoling - can you confirm?

**Comment by yunhaoling** [comment]
oops, my bad -- those files sneaked in..
thanks @bluca! I'll create a PR to remove all of them

**Comment by bluca** [comment]
Thanks! Would be great to have a point release after that if possible, so I can import the fixed tarball in Debian/Ubuntu.

**Comment by bluca** [comment]
hi - any update on this? I'd like to upload the latest bug fix release before the Debian 11 freeze, but it's in 3 weeks so time is running out

**Comment by yunhaoling** [comment]
hey @bluca , I have just created a PR: https://github.com/Azure/azure-uamqp-python/pull/211.

>  point release 

do you mean the release on github?
![image](https://user-images.githubusercontent.com/47871814/108248185-613d0c80-7108-11eb-8d53-e366bdc1de7a.png)

**Comment by bluca** [comment]
Yes, I meant a new release, it would make my life quite a bit easier if that were possible. Thank you!

**Comment by yunhaoling** [comment]
hey @bluca , I have merged the PR removing all the executables: https://github.com/Azure/azure-uamqp-python/pull/211

We're planning to do a uamqp v1.2.15 release on March1 as we also want to address some other issues in the next release.
would that be acceptable to you to wait for one more week?

**Comment by bluca** [comment]
sure that would be fine - thank you very much!
