### ISSUE TITLE
Outdated doctring for SendClient

### ISSUE THREAD

**Issue by vishnureddy17** [Azure/azure-uamqp-python#266]
It seems like the docstring for `SendClient` is outdated, as I'm able to use `uamqp.authentication.JWTTokenAuth`, which is not included in this list:

```
    :param auth: Authentication for the connection. This should be one of the subclasses of
     uamqp.authentication.AMQPAuth. Currently this includes:
        - uamqp.authentication.SASLAnonymous
        - uamqp.authentication.SASLPlain
        - uamqp.authentication.SASTokenAuth
```

**Comment by yunhaoling** [comment]
hey @vishnureddy17 , thanks for the feedback. I'll update the docstring!

**Comment by yunhaoling** [comment]
hey @vishnureddy17 , we have updated the docstring for SendClient (as well as other clients that takes JWTTokenAuth now), thanks for your feedback.
