### ISSUE TITLE
Implement Event Processor Host pattern

### ISSUE THREAD

**Issue by torosent** [Azure/azure-uamqp-python#3]
Implement Event Processor Host pattern like in the previous Python SDK 
https://github.com/Azure/azure-event-hubs-python/tree/develop/eventprocessorhost

**Comment by annatisch** [comment]
The Event Processor Host and Event Hubs SDK are currently being updated to rely on uAMQP.
The ongoing work is being done here:
https://github.com/annatisch/azure-event-hubs-python/tree/uamqp

**Comment by annatisch** [comment]
First preview release of the new azure-eventhub SDK with EPH is now published:
https://github.com/Azure/azure-event-hubs-python/tree/develop
https://pypi.org/project/azure-eventhub/
