### ISSUE TITLE
Wrong timeout description

### ISSUE THREAD

**Issue by Cicicok** [Azure/azure-uamqp-python#32]
___init__.py,_ methods: _receive_messages, receive_message_ you can find this text:

> :param timeout: The timeout in seconds after which to return None if no messages
>      are retrieved. If set to `0` (the default), the receiver will not timeout and
>      will continue to wait for messages until interrupted.

But it's actualy in millisecond as written in the _class ReceiveClient(AMQPClient)_ documentation from which are those methods created.

**Comment by annatisch** [comment]
Aaaah you are very correct - well spotted! I will update ASAP :)

**Comment by annatisch** [comment]
I'm pushed the update to master - which means it should get picked up for the docs generation and will be in published library itself in the next release (probably a few weeks away unless an urgent bug pops up).

Thanks again for the report!
