### ISSUE TITLE
Can't install the package on Ubuntu virtual machine though M1

### ISSUE THREAD

**Issue by atlid8** [Azure/azure-uamqp-python#324]
- **UAMQP Package Version**:  1.5.3
- **Operating System**: Ubuntu
- **Python Version**: 3.8.13

**Describe the bug**
Can't pip install UAMQP on Ubuntu QEMU thought M1

**To Reproduce**
1. apt-get update
2. apt-get install -y build-essential libssl-dev uuid-dev cmake libcurl4-openssl-dev pkg-config python3-dev python3-pip
2.  pip3 install uamqp --no-binary :all:

**Expected behavior**
Package is installed

**Additional context**
Output is:
pip3 install uamqp --no-binary :all:
Collecting uamqp
  Using cached uamqp-1.5.3.tar.gz (4.4 MB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: certifi>=2017.4.17 in ./venv/lib/python3.8/site-packages (from uamqp) (2020.6.20)
Requirement already satisfied: six~=1.0 in ./venv/lib/python3.8/site-packages (from uamqp) (1.15.0)
Skipping wheel build for uamqp, due to binaries being disabled for it.
Installing collected packages: uamqp
  Running setup.py install for uamqp ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for uamqp did not run successfully.
  │ exit code: 1
  ╰─> [257 lines of output]
      running install
      running build
      running build_py
      creating build
      creating build/lib.linux-aarch64-3.8
      creating build/lib.linux-aarch64-3.8/uamqp
      copying uamqp/compat.py -> build/lib.linux-aarch64-3.8/uamqp
      copying uamqp/sender.py -> build/lib.linux-aarch64-3.8/uamqp
      copying uamqp/mgmt_operation.py -> build/lib.linux-aarch64-3.8/uamqp
      copying uamqp/client.py -> build/lib.linux-aarch64-3.8/uamqp
      copying uamqp/connection.py -> build/lib.linux-aarch64-3.8/uamqp
      copying uamqp/session.py -> build/lib.linux-aarch64-3.8/uamqp
      copying uamqp/__init__.py -> build/lib.linux-aarch64-3.8/uamqp
      copying uamqp/utils.py -> build/lib.linux-aarch64-3.8/uamqp
      copying uamqp/message.py -> build/lib.linux-aarch64-3.8/uamqp
      copying uamqp/types.py -> build/lib.linux-aarch64-3.8/uamqp
      copying uamqp/receiver.py -> build/lib.linux-aarch64-3.8/uamqp
      copying uamqp/errors.py -> build/lib.linux-aarch64-3.8/uamqp
      copying uamqp/constants.py -> build/lib.linux-aarch64-3.8/uamqp
      copying uamqp/address.py -> build/lib.linux-aarch64-3.8/uamqp
      creating build/lib.linux-aarch64-3.8/uamqp/async_ops
      copying uamqp/async_ops/session_async.py -> build/lib.linux-aarch64-3.8/uamqp/async_ops
      copying uamqp/async_ops/receiver_async.py -> build/lib.linux-aarch64-3.8/uamqp/async_ops
      copying uamqp/async_ops/sender_async.py -> build/lib.linux-aarch64-3.8/uamqp/async_ops
      copying uamqp/async_ops/client_async.py -> build/lib.linux-aarch64-3.8/uamqp/async_ops
      copying uamqp/async_ops/__init__.py -> build/lib.linux-aarch64-3.8/uamqp/async_ops
      copying uamqp/async_ops/connection_async.py -> build/lib.linux-aarch64-3.8/uamqp/async_ops
      copying uamqp/async_ops/mgmt_operation_async.py -> build/lib.linux-aarch64-3.8/uamqp/async_ops
      copying uamqp/async_ops/utils.py -> build/lib.linux-aarch64-3.8/uamqp/async_ops
      creating build/lib.linux-aarch64-3.8/uamqp/authentication
      copying uamqp/authentication/common.py -> build/lib.linux-aarch64-3.8/uamqp/authentication
      copying uamqp/authentication/cbs_auth.py -> build/lib.linux-aarch64-3.8/uamqp/authentication
      copying uamqp/authentication/cbs_auth_async.py -> build/lib.linux-aarch64-3.8/uamqp/authentication
      copying uamqp/authentication/__init__.py -> build/lib.linux-aarch64-3.8/uamqp/authentication
      running egg_info
      writing uamqp.egg-info/PKG-INFO
      writing dependency_links to uamqp.egg-info/dependency_links.txt
      writing requirements to uamqp.egg-info/requires.txt
      writing top-level names to uamqp.egg-info/top_level.txt
      reading manifest file 'uamqp.egg-info/SOURCES.txt'
      reading manifest template 'MANIFEST.in'
      writing manifest file 'uamqp.egg-info/SOURCES.txt'
      copying uamqp/c_uamqp.c -> build/lib.linux-aarch64-3.8/uamqp
      running build_ext
      will build uamqp in build/temp.linux-aarch64-3.8/cmake
      Building with generator flags: -G "Unix Makefiles"
      calling cmake /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/ -G "Unix Makefiles" -Duse_openssl:bool=ON -Duse_default_uuid:bool=ON  -Duse_builtin_httpapi:bool=ON  -Dskip_samples:bool=ON -DCMAKE_POSITION_INDEPENDENT_CODE=TRUE -DCMAKE_BUILD_TYPE=Release
      -- The C compiler identification is GNU 11.2.0
      -- The CXX compiler identification is GNU 11.2.0
      -- Detecting C compiler ABI info
      -- Detecting C compiler ABI info - done
      -- Check for working C compiler: /usr/bin/cc - skipped
      -- Detecting C compile features
      -- Detecting C compile features - done
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Deprecation Warning at deps/azure-macro-utils-c/CMakeLists.txt:4 (cmake_minimum_required):
        Compatibility with CMake < 2.8.12 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      CMake Warning (dev) at deps/azure-macro-utils-c/CMakeLists.txt:14 (option):
        Policy CMP0077 is not set: option() honors normal variables.  Run "cmake
        --help-policy CMP0077" for policy details.  Use the cmake_policy command to
        set the policy and suppress this warning.
      
        For compatibility with older versions of CMake, option is clearing the
        normal variable 'run_int_tests'.
      This warning is for project developers.  Use -Wno-dev to suppress it.
      
      CMake Deprecation Warning at deps/umock-c/CMakeLists.txt:4 (cmake_minimum_required):
        Compatibility with CMake < 2.8.12 will be removed from a future version of
        CMake.
      
        Update the VERSION argument <min> value or use a ...<max> suffix to tell
        CMake that the project does not need compatibility with older versions.
      
      
      -- Looking for include file stdint.h
      -- Looking for include file stdint.h - found
      -- Looking for include file stdbool.h
      -- Looking for include file stdbool.h - found
      -- target architecture: GENERIC
      -- Performing Test CXX_FLAG_CXX11
      -- Performing Test CXX_FLAG_CXX11 - Success
      -- Found OpenSSL: /usr/lib/aarch64-linux-gnu/libcrypto.so (found version "3.0.2")
      -- target architecture: GENERIC
      -- Configuring done
      -- Generating done
      -- Build files have been written to: /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/build/temp.linux-aarch64-3.8/cmake
      calling cmake --build . --config Release
      [  0%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/azure_base32.c.o
      [  1%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/azure_base64.c.o
      [  2%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/buffer.c.o
      [  3%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/constbuffer_array.c.o
      [  4%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/constbuffer_array_batcher.c.o
      [  5%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/connection_string_parser.c.o
      [  6%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/constbuffer.c.o
      [  7%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/consolelogger.c.o
      [  8%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/crt_abstractions.c.o
      [  9%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/constmap.c.o
      [ 10%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/doublylinkedlist.c.o
      [ 11%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/gballoc.c.o
      [ 12%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/gbnetwork.c.o
      [ 13%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/gb_stdio.c.o
      [ 14%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/gb_time.c.o
      [ 15%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/gb_rand.c.o
      [ 16%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/hmac.c.o
      [ 17%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/hmacsha256.c.o
      [ 18%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/xio.c.o
      [ 19%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/singlylinkedlist.c.o
      [ 20%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/map.c.o
      [ 21%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/sastoken.c.o
      [ 22%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/sha1.c.o
      [ 23%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/sha224.c.o
      [ 24%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/sha384-512.c.o
      [ 25%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/strings.c.o
      [ 26%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/string_token.c.o
      [ 27%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/string_tokenizer.c.o
      [ 28%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/uuid.c.o
      [ 29%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/urlencode.c.o
      [ 30%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/usha.c.o
      [ 31%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/vector.c.o
      [ 32%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/xlogging.c.o
      [ 33%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/optionhandler.c.o
      [ 34%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/memory_data.c.o
      [ 35%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/agenttime.c.o
      [ 36%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/condition_pthreads.c.o
      [ 37%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/lock_pthreads.c.o
      [ 38%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/platform_linux.c.o
      [ 39%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/socketio_berkeley.c.o
      [ 40%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/tickcounter_linux.c.o
      [ 41%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/threadapi_pthreads.c.o
      [ 42%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/uniqueid_stub.c.o
      [ 43%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/envvariable.c.o
      [ 44%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/dns_resolver_sync.c.o
      [ 45%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/linux_time.c.o
      [ 46%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/httpapiex.c.o
      [ 47%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/httpapiexsas.c.o
      [ 48%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/httpheaders.c.o
      [ 49%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/httpapi_compact.c.o
      [ 50%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/src/http_proxy_io.c.o
      [ 51%] Building C object deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/tlsio_openssl.c.o
      /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c: In function ‘engine_destroy’:
      /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:762:9: error: ‘ENGINE_free’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
        762 |         ENGINE_free(tls->engine); // Release structural reference.
            |         ^~~~~~~~~~~
      In file included from /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:9:
      /usr/include/openssl/engine.h:493:27: note: declared here
        493 | OSSL_DEPRECATEDIN_3_0 int ENGINE_free(ENGINE *e);
            |                           ^~~~~~~~~~~
      /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c: In function ‘engine_load’:
      /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:772:5: error: ‘ENGINE_by_id’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
        772 |     tls->engine = ENGINE_by_id(tls->engine_id);
            |     ^~~
      In file included from /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:9:
      /usr/include/openssl/engine.h:336:31: note: declared here
        336 | OSSL_DEPRECATEDIN_3_0 ENGINE *ENGINE_by_id(const char *id);
            |                               ^~~~~~~~~~~~
      /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c: In function ‘add_certificate_to_store’:
      /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:961:24: error: assignment discards ‘const’ qualifier from pointer target type [-Werror=discarded-qualifiers]
        961 |             bio_method = BIO_s_mem();
            |                        ^
      /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c: In function ‘create_openssl_instance’:
      /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:1058:9: error: ‘TLSv1_2_method’ is deprecated: Since OpenSSL 1.1.0 [-Werror=deprecated-declarations]
       1058 |         method = TLSv1_2_method();
            |         ^~~~~~
      In file included from /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:5:
      /usr/include/openssl/ssl.h:2020:50: note: declared here
       2020 | OSSL_DEPRECATEDIN_1_1_0 __owur const SSL_METHOD *TLSv1_2_method(void); /* TLSv1.2 */
            |                                                  ^~~~~~~~~~~~~~
      /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:1062:9: error: ‘TLSv1_1_method’ is deprecated: Since OpenSSL 1.1.0 [-Werror=deprecated-declarations]
       1062 |         method = TLSv1_1_method();
            |         ^~~~~~
      In file included from /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:5:
      /usr/include/openssl/ssl.h:2012:50: note: declared here
       2012 | OSSL_DEPRECATEDIN_1_1_0 __owur const SSL_METHOD *TLSv1_1_method(void); /* TLSv1.1 */
            |                                                  ^~~~~~~~~~~~~~
      /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:1066:9: error: ‘TLSv1_method’ is deprecated: Since OpenSSL 1.1.0 [-Werror=deprecated-declarations]
       1066 |         method = TLSv1_method();
            |         ^~~~~~
      In file included from /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:5:
      /usr/include/openssl/ssl.h:2004:50: note: declared here
       2004 | OSSL_DEPRECATEDIN_1_1_0 __owur const SSL_METHOD *TLSv1_method(void); /* TLSv1.0 */
            |                                                  ^~~~~~~~~~~~
      /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c: In function ‘tlsio_openssl_init’:
      /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:1224:5: error: ‘ERR_load_BIO_strings’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
       1224 |     ERR_load_BIO_strings();
            |     ^~~~~~~~~~~~~~~~~~~~
      In file included from /usr/include/openssl/cryptoerr.h:17,
                       from /usr/include/openssl/crypto.h:38,
                       from /usr/include/openssl/comp.h:22,
                       from /usr/include/openssl/ssl.h:28,
                       from /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:5:
      /usr/include/openssl/cryptoerr_legacy.h:31:27: note: declared here
         31 | OSSL_DEPRECATEDIN_3_0 int ERR_load_BIO_strings(void);
            |                           ^~~~~~~~~~~~~~~~~~~~
      /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c: In function ‘tlsio_openssl_deinit’:
      /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:1252:5: error: ‘ERR_remove_thread_state’ is deprecated: Since OpenSSL 1.1.0 [-Werror=deprecated-declarations]
       1252 |     ERR_remove_thread_state(NULL);
            |     ^~~~~~~~~~~~~~~~~~~~~~~
      In file included from /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:6:
      /usr/include/openssl/err.h:473:30: note: declared here
        473 | OSSL_DEPRECATEDIN_1_1_0 void ERR_remove_thread_state(void *);
            |                              ^~~~~~~~~~~~~~~~~~~~~~~
      /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c: In function ‘tlsio_openssl_setoption’:
      /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:1724:13: error: ‘ENGINE_load_builtin_engines’ is deprecated: Since OpenSSL 3.0 [-Werror=deprecated-declarations]
       1724 |             ENGINE_load_builtin_engines();
            |             ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      In file included from /tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/src/vendor/azure-uamqp-c/deps/azure-c-shared-utility/adapters/tlsio_openssl.c:9:
      /usr/include/openssl/engine.h:358:28: note: declared here
        358 | OSSL_DEPRECATEDIN_3_0 void ENGINE_load_builtin_engines(void);
            |                            ^~~~~~~~~~~~~~~~~~~~~~~~~~~
      cc1: all warnings being treated as errors
      gmake[2]: *** [deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/build.make:790: deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/adapters/tlsio_openssl.c.o] Error 1
      gmake[1]: *** [CMakeFiles/Makefile2:943: deps/azure-c-shared-utility/CMakeFiles/aziotsharedutil.dir/all] Error 2
      gmake: *** [Makefile:146: all] Error 2
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/setup.py", line 260, in <module>
          setup(
        File "/****/venv/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/****/venv/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/usr/lib/python3.8/distutils/command/install.py", line 589, in run
          self.run_command('build')
        File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/usr/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/setup.py", line 134, in run
          self.build_cmake(ext)
        File "/tmp/pip-install-m_ohs_ed/uamqp_394c3982453e415e8bff5eb9e0480092/setup.py", line 188, in build_cmake
          subprocess.check_call(joined_cmd, shell=True, universal_newlines=True, env=build_env)
        File "/usr/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command 'cmake --build . --config Release' returned non-zero exit status 2.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> uamqp

**Comment by atliunnsteinsson** [comment]
I can install under local python 3.10 but not on env running 3.8

**Comment by dustinchilson** [comment]
If you can, drop the ubuntu vm down to 20.04, this is due to 22.04's use of OpenSSL 3.0

https://github.com/Azure/azure-uamqp-python/issues/276

https://github.com/Azure/azure-c-shared-utility/discussions/566

**Comment by kashifkhan** [comment]
Hello, sorry for the late reply. I'm working on the issue and was able to build uamqp on Ubuntu 22.04 using the following.

If you are using the Event Hubs SDK I would encourage you to try the new version 5.11.1 which is running on a new python based AMQP stack and doesn`t require uamqp. We will be doing the same for Service Bus shortly.

```dockerfile
FROM ubuntu:22.04
RUN apt-get update -y
RUN apt-get install -y build-essential libssl-dev uuid-dev cmake libcurl4-openssl-dev pkg-config python3-dev python3-pip git
RUN git clone --single-branch --branch fix_openssl3 https://github.com/kashifkhan/azure-uamqp-python.git
RUN pip3 install --no-binary :all: azure-uamqp-python/```
