### ISSUE TITLE
Rebuild ManyLinux1_64bit_patch dockerfile w/out external dependencies

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-uamqp-python#329]
The [dockerfile](https://github.com/Azure/azure-uamqp-python/blob/master/utils/ManyLinux1_64bit_patch/Dockerfile) takes a dependency on quay.io.

Need to rebuild ourselves. Other references:

- [Python package authority build folder](https://github.com/pypa/manylinux/tree/main/docker)

We are going to need to build the image ourselves.

**Comment by kashifkhan** [comment]
Closed with #339, building wheels with cibuildwheel
