### ISSUE TITLE
1.6.0 tag missing in git repository

### ISSUE THREAD

**Issue by major** [Azure/azure-uamqp-python#340]
It looks like version 1.6.0 made it to PyPi, but the tag for 1.6.0 is missing from the git repository. Could you add a tag/release? Thanks!

**Comment by kashifkhan** [comment]
Hi @major, sorry for the delay, I have gone ahead and created the tag/release [here](https://github.com/Azure/azure-uamqp-python/releases/tag/v.1.60)

**Comment by major** [comment]
Thank you!
