### ISSUE TITLE
Not able to send message after using subject in MessageProperties

### ISSUE THREAD

**Issue by mi-dst** [Azure/azure-uamqp-python#35]
First of all I want to state that I am rather new to AMQP, so I may have misunderstood something here and if so, sorry...

I was expecting to be able to set the subject of a message to be sent, however when I try to send it I get a:

> DEBUG:uamqp.client:Message error, retrying. Attempts: 1, Error: ClientMessageError('ErrorCodes.ClientError: expected bytes, uamqp.c_uamqp.StringValue found')

I see the same error if it try to use the get_properties_obj() function, which leads me to believe the following is a shortcut to reproduce my problem:

> props = uamqp.message.MessageProperties(subject='test')
props.get_properties_obj()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "X:\env\lib\site-packages\uamqp\message.py", line 753, in get_properties_obj
    self._set_attr('subject', properties)
  File "X:\env\lib\site-packages\uamqp\message.py", line 742, in _set_attr
    setattr(properties, attr, attr_value)
  File ".\src/properties.pyx", line 140, in uamqp.c_uamqp.cProperties.subject.__set__
TypeError: expected bytes, uamqp.c_uamqp.StringValue found 

If I instead set the message_id, everything seems to work properly.
I am currently running python 3.7 under windows with uamqp 1.0.0 installed by pip.

Let me end this post with a big **thank you** for providing this module. I am hoping to access an Azure servicebus using AMQP instead of the somewhat sluggish (in comparison) REST api.

**Comment by annatisch** [comment]
Thanks for the report @mi-dst!

You're right - this does appear to be a bug - as we are converting the subject property into an AMQP encoded object when it should be a string/bytes.

I will get a patch out asap :)

Thanks again!

**Comment by mi-dst** [comment]
Ah, yes. I am not using get_properties_obj() normally. I just tried to make the problem as easy to reproduce as possible for you, but thanks for looking out for me :)

I will keep my eyes peeled for the patch.

Thanks for your quick feedback!

**Comment by annatisch** [comment]
Thanks for your patience @mi-dst - v1.0.1 is now released with a fix. :)

**Comment by mi-dst** [comment]
Thanks for the quick update. However I am sad to report that I still cannot seem to get the subject-property working. I do get a different error with 1.0.1 though.

When sending a message I now get:
> DEBUG:uamqp.client:Message error, retrying. Attempts: 1, Error: ClientMessageError("ErrorCodes.ClientError: 'bytes' object has no attribute '_c_value'")

Again I believe the quickest way to test it is:
> props = uamqp.message.MessageProperties(subject='hello')
> props.get_properties_obj()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\uamqp-test\.pyenv\lib\site-packages\uamqp\message.py", line 752, in get_properties_obj
    self._set_attr('subject', properties)
  File "C:\uamqp-test\.pyenv\lib\site-packages\uamqp\message.py", line 741, in _set_attr
    setattr(properties, attr, attr_value)
  File ".\src/properties.pyx", line 142, in uamqp.c_uamqp.cProperties.subject.__set__
AttributeError: 'bytes' object has no attribute '_c_value'

Sorry for bringing you bad new just before the weekend...

**Comment by annatisch** [comment]
That's strange - I wonder why [my test](https://github.com/Azure/azure-uamqp-python/blob/master/samples/test_azure_event_hubs_send.py#L49) didn't catch that...
Doh... okay - another patch on it's way....

**Comment by annatisch** [comment]
I'm hoping to include this patch with a couple of other small fixes - release should be out sometime this coming week. Thanks again for your patience :)

**Comment by mi-dst** [comment]
Sounds great! Thanks for the feedback!

**Comment by annatisch** [comment]
Okay - this should now *actually* be resolved in 1.0.2 :)
I actually found some issues in setting a couple of the other message properties as well so a good find!
Sorry it took so long - one of the other changes I wanted to add to this release was giving me headaches.

**Comment by mi-dst** [comment]
Unfortunately I will have to restrain myself from testing this for a couple of days as I have other pressing matters to handle. I will get there soon though! :)

Thanks again for your help!
