### ISSUE TITLE
Version tags on Github are broken

### ISSUE THREAD

**Issue by bluca** [Azure/azure-uamqp-python#366]
Git tags until 1.5.3:

https://github.com/Azure/azure-uamqp-python/releases/tag/v1.5.0
https://github.com/Azure/azure-uamqp-python/releases/tag/v1.5.1
https://github.com/Azure/azure-uamqp-python/releases/tag/v1.5.2
https://github.com/Azure/azure-uamqp-python/releases/tag/v1.5.3

Version tags since 1.6.1:

https://github.com/Azure/azure-uamqp-python/releases/tag/v.1.6.1
https://github.com/Azure/azure-uamqp-python/releases/tag/v.1.6.3
https://github.com/Azure/azure-uamqp-python/releases/tag/v.1.6.4

There is an extra `.` between `v` and the first digit. This breaks all automation pulling from github, please fix it by creating the correctly named tags for all affected versions and pushing them, and deleting the wrong ones.

Also there is a completely broken `v.1.60` tag instead of `v1.6.0`. Versions are sorted by number, not date, so `1.60` will always result as newer than `1.6.x`. Please fix that too by pushing `v1.6.0` and deleting `v.1.60`

https://github.com/Azure/azure-uamqp-python/releases/tag/v.1.60

**Comment by bluca** [comment]
@kashifkhan could you please look into this? We can't upload to Debian/Ubuntu until it's fixed as it breaks all workflows

**Comment by kashifkhan** [comment]
@bluca working on this right now, sorry about the delay

**Comment by bluca** [comment]
thank you

**Comment by kashifkhan** [comment]
updated and fixed. Appreciate the patience @bluca

**Comment by bluca** [comment]
that's great, thank you
