### ISSUE TITLE
Windows 32 bit wheels removed

### ISSUE THREAD

**Issue by pythonweb2** [Azure/azure-uamqp-python#410]
- **UAMQP Package Version**: 1.6.11
- **Operating System**: Windows (32-bit)
- **Python Version**: 3.8

**Describe the bug**

This package no longer ships with 32 bit windows wheels

**To Reproduce**
1. Try to install with 32 bit python on windows

**Expected behavior**

In the past the wheels used to exist. I'm not sure why they are no longer there, nothing was mentioned in the release notes.

**Screenshots**

**Additional context**

**Comment by pythonweb2** [comment]
Looks like this was intentional, based on #408, but I don't see any reason why?

**Comment by kashifkhan** [comment]
Hi @pythonweb2, we had stopped publishing 32-bit wheels for mac and linux two years ago and were mistakenly pushing windows wheels till recently. Internally the test infrastructure from them was also removed, so they were not thoroughly tested like their 64 bit counterparts. Thats why we stopped 32 bit builds of windows.

**Comment by kashifkhan** [comment]
@pythonweb2 if there is a need for windows 32 builds, they can be built using cibuildwheel and the pyproject toml file has the information needed to do so.
