### ISSUE TITLE
Support for websockets

### ISSUE THREAD

**Issue by annatisch** [Azure/azure-uamqp-python#43]
Required for Azure Event Hub SDK as documented in [issue #67](https://github.com/Azure/azure-event-hubs-python/issues/67).

**Comment by dvincentwest** [comment]
would love to see this feature implemented as I have the same issue as mention in [issue #67](https://github.com/Azure/azure-event-hubs-python/issues/67)

Is there anything close at this point or still far off?  I can volunteer to help implement with some guidance

**Comment by yunhaoling** [comment]
sorry for this very late update, but we have already got websocket supported for uamqp and azure-eventhub .

for azure-eventhub library, set `transport_type` to `azure.eventhub.TransportType.AmqpOverWebsocket` to enable websocket connection during client creation: [TransportType](https://github.com/Azure/azure-sdk-for-python/blob/main/sdk/eventhub/azure-eventhub/azure/eventhub/_producer_client.py#L59-L63)
