### ISSUE TITLE
Async send stuck

### ISSUE THREAD

**Issue by zach-b** [Azure/azure-uamqp-python#53]
I am using the client to send messages to the azure service bus. I noticed that some messages were never delivered.

The SendClientAsync.send_message_async method is stuck in the loop 
```
while any([m for m in pending_batch if m.state not in constants.DONE_STATES]):    
    await self.do_work_async()
```

The message is in the state <MessageState.WaitingToBeSent: 0> and is not in self._pending_messages, so I am thinking that it might have never been added to the list due to some concurrency issue ?

**Comment by annatisch** [comment]
Thanks @zach-b!
Interesting that you're not seeing the message in _pending_messages - could I please see a code snippet that you're using to send?

A couple of additional questions:
- Which OS and Python version are running on?
- How much data is in the message that is hanging?

We have a current issue in Event Hubs for messages with content greater than ~128kb getting stuck which may be related:
https://github.com/Azure/azure-event-hubs-python/issues/76

**Comment by zach-b** [comment]
Thanks for your answer

The message is sent using the following method
```
    async def send(self, msg, ttl=None):
            ttl_header = None
            if ttl is not None:
                ttl_header = MessageHeader()
                ttl_header.time_to_live = ttl * 1000
            umsg = UamqpMessage(
                body=msg.body,
                application_properties=msg.headers,
                header=ttl_header
            )
            await self._sender.send_message_async(umsg)
```
The OS is Debian 8, I did not check the content of the messages yet, I'll make sure to do it if the bug occurs again tonight (or else on monday), but the messages should be rather small with a few headers and no body. I'll try to isolate and reproduce the bug on monday

**Comment by zach-b** [comment]
So I investigated a bit further. and the content of the messages is indeed as described above (nothing out of the ordinary...).
I was not able to reproduce the bug on a simple case for the moment, my guess is that it is due to concurrency issue with the pending messages list, but I cannot know for sure. I'll try again in the following days

**Comment by annatisch** [comment]
Thanks for the follow-up @zach-b - yes I agree that seems to be the likely cause. Especially given that it's so intermittent. I will investigate.

**Comment by zach-b** [comment]
I tried adding a lock to the async methods modyfing the pending messages list, I'm letting it run for some time to see if any message still gets stuck (it usually happened a few times per hour). I'll make a PR if it's successful

**Comment by annatisch** [comment]
Oh you're a legend! Thank you so much for your continued investigations! I look forward to hearing how it goes :)

**Comment by zach-b** [comment]
Haha no problem it's really a minor modification.The bug seems to be gone now. I guess the issue was occuring when adding a message while the coroutine `self._filter_pending_async()` was running.

I'm opening the PR so you can check the changes, thanks for your quick answers !

**Comment by thedrow** [comment]
Shouldn't this issue be closed?
Seems like Github didn't close it automatically.

**Comment by thedrow** [comment]
@zach-b Ping? ^

**Comment by annatisch** [comment]
Closing for now - @zach-b - if you're still experiencing this issue please let us know and we can re-open.
