### ISSUE TITLE
Re-Enable Python 3.8a in test matrix for azure-pipelines

### ISSUE THREAD

**Issue by scbedd** [Azure/azure-uamqp-python#73]
The code is still present, commented. However, build failures against 3.8a are preventing passes. Given that this a pre-release python version, we do not want to block a release of uamqp on it. Investigation will happen the next release of the uamqp python library.

@annatisch FYI
[Source issue ](https://github.com/Azure/azure-sdk-for-python/issues/5156)

**Comment by bsiegel** [comment]
Build matrix now runs with released Python 3.8 however Python 3.9a1 is now out and we might want to start running against that at some point.
